@host = https://api-missrona.sousa.cloud
###

# @name addFeeling

POST {{host}}/feelings HTTP/1.1
Content-Type: application/json
personaId: "aaa"

{
  "status": 1,
  "location": [59.3365601, 18.0321006]
}
